### ISSUE TITLE
Zygisk not working on PixelOS

### ISSUE THREAD

**Issue by danielPenaAndres** [HuskyDG/magisk-files#134]
Since 2 weeks more or less zygisk disabled itself and its not working, it just shows No on the main screen no matter if its disabled or enabled in settings.
Ive tried to install different builds(debug,release, canary) to no avail, ive even installed this version https://github.com/HuskyDG/magisk-files/issues/129

**Comment by antivirtel** [comment]
Same here, just upgraded to Android 14 (LOS 20 -> 21), then Zygisk doesn't work anymore, can't pass integrity check without Zygisk modules.

**Comment by amritpal2489** [comment]
I just upgraded to A15 over OTA and used the install to inactive slot before rebooting. Now am facing the same issue with zygisk not getting enabled. Is there any solution to this issue?

**Comment by PadMadoff** [comment]
> Same here, just upgraded to Android 14 (LOS 20 -> 21), then Zygisk doesn't work anymore, can't pass integrity check without Zygisk modules. I'm on OnePlus 6

Nubia Red Magic 9 Pro, same issue, android 14 didn't work zygisk

**Comment by PriMieon** [comment]
Same on my pixel fold. Zygisk simply won't work

**Comment by Blazzycrafter** [comment]
Same for Grapheen os...

**Comment by LovecraftianGodsKiller** [comment]
I've been using Magisk Delta since I got my pixel 7 back in like april or may. and I'm running the stock ROM and zygisk has always worked for me.
I'm currently on the latest QPR build for Android 15 QPR 1.
I ALWAYS update by downloading the ota, extracting the payload.bin, copying the init_boot.img file to my phone, patching it with magisk delta, copying it back to my computer, flash the OTA zip with adb sideloading, booting into fastboot when the flashing finishes, then flashing the patched init_boot.img file, then rebooting.
